/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritingVocabRouteImport } from './routes/writing-vocab'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as TestRouteImport } from './routes/test'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as SpeakingVocabRouteImport } from './routes/speaking-vocab'
import { Route as IeltsReadingRouteImport } from './routes/ielts-reading'
import { Route as IeltsListeningRouteImport } from './routes/ielts-listening'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IeltsReadingIndexRouteImport } from './routes/ielts-reading.index'
import { Route as IeltsListeningIndexRouteImport } from './routes/ielts-listening.index'
import { Route as WritingVocabViewRouteImport } from './routes/writing-vocab_.view'
import { Route as WritingVocabTestRouteImport } from './routes/writing-vocab_.test'
import { Route as SpeakingVocabViewRouteImport } from './routes/speaking-vocab_.view'
import { Route as SpeakingVocabTestRouteImport } from './routes/speaking-vocab_.test'
import { Route as IeltsReadingCambridgeNumRouteImport } from './routes/ielts-reading.$cambridgeNum'
import { Route as IeltsListeningCambridgeNumRouteImport } from './routes/ielts-listening.$cambridgeNum'
import { Route as IeltsReadingCambridgeNumIndexRouteImport } from './routes/ielts-reading.$cambridgeNum.index'
import { Route as IeltsListeningCambridgeNumIndexRouteImport } from './routes/ielts-listening.$cambridgeNum.index'
import { Route as IeltsReadingCambridgeNumTestNumRouteImport } from './routes/ielts-reading.$cambridgeNum.$testNum'
import { Route as IeltsListeningCambridgeNumTestNumRouteImport } from './routes/ielts-listening.$cambridgeNum.$testNum'

const WritingVocabRoute = WritingVocabRouteImport.update({
  id: '/writing-vocab',
  path: '/writing-vocab',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakingVocabRoute = SpeakingVocabRouteImport.update({
  id: '/speaking-vocab',
  path: '/speaking-vocab',
  getParentRoute: () => rootRouteImport,
} as any)
const IeltsReadingRoute = IeltsReadingRouteImport.update({
  id: '/ielts-reading',
  path: '/ielts-reading',
  getParentRoute: () => rootRouteImport,
} as any)
const IeltsListeningRoute = IeltsListeningRouteImport.update({
  id: '/ielts-listening',
  path: '/ielts-listening',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IeltsReadingIndexRoute = IeltsReadingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IeltsReadingRoute,
} as any)
const IeltsListeningIndexRoute = IeltsListeningIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IeltsListeningRoute,
} as any)
const WritingVocabViewRoute = WritingVocabViewRouteImport.update({
  id: '/writing-vocab_/view',
  path: '/writing-vocab/view',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingVocabTestRoute = WritingVocabTestRouteImport.update({
  id: '/writing-vocab_/test',
  path: '/writing-vocab/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakingVocabViewRoute = SpeakingVocabViewRouteImport.update({
  id: '/speaking-vocab_/view',
  path: '/speaking-vocab/view',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakingVocabTestRoute = SpeakingVocabTestRouteImport.update({
  id: '/speaking-vocab_/test',
  path: '/speaking-vocab/test',
  getParentRoute: () => rootRouteImport,
} as any)
const IeltsReadingCambridgeNumRoute =
  IeltsReadingCambridgeNumRouteImport.update({
    id: '/$cambridgeNum',
    path: '/$cambridgeNum',
    getParentRoute: () => IeltsReadingRoute,
  } as any)
const IeltsListeningCambridgeNumRoute =
  IeltsListeningCambridgeNumRouteImport.update({
    id: '/$cambridgeNum',
    path: '/$cambridgeNum',
    getParentRoute: () => IeltsListeningRoute,
  } as any)
const IeltsReadingCambridgeNumIndexRoute =
  IeltsReadingCambridgeNumIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => IeltsReadingCambridgeNumRoute,
  } as any)
const IeltsListeningCambridgeNumIndexRoute =
  IeltsListeningCambridgeNumIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => IeltsListeningCambridgeNumRoute,
  } as any)
const IeltsReadingCambridgeNumTestNumRoute =
  IeltsReadingCambridgeNumTestNumRouteImport.update({
    id: '/$testNum',
    path: '/$testNum',
    getParentRoute: () => IeltsReadingCambridgeNumRoute,
  } as any)
const IeltsListeningCambridgeNumTestNumRoute =
  IeltsListeningCambridgeNumTestNumRouteImport.update({
    id: '/$testNum',
    path: '/$testNum',
    getParentRoute: () => IeltsListeningCambridgeNumRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ielts-listening': typeof IeltsListeningRouteWithChildren
  '/ielts-reading': typeof IeltsReadingRouteWithChildren
  '/speaking-vocab': typeof SpeakingVocabRoute
  '/statistics': typeof StatisticsRoute
  '/test': typeof TestRoute
  '/vocabulary': typeof VocabularyRoute
  '/writing-vocab': typeof WritingVocabRoute
  '/ielts-listening/$cambridgeNum': typeof IeltsListeningCambridgeNumRouteWithChildren
  '/ielts-reading/$cambridgeNum': typeof IeltsReadingCambridgeNumRouteWithChildren
  '/speaking-vocab/test': typeof SpeakingVocabTestRoute
  '/speaking-vocab/view': typeof SpeakingVocabViewRoute
  '/writing-vocab/test': typeof WritingVocabTestRoute
  '/writing-vocab/view': typeof WritingVocabViewRoute
  '/ielts-listening/': typeof IeltsListeningIndexRoute
  '/ielts-reading/': typeof IeltsReadingIndexRoute
  '/ielts-listening/$cambridgeNum/$testNum': typeof IeltsListeningCambridgeNumTestNumRoute
  '/ielts-reading/$cambridgeNum/$testNum': typeof IeltsReadingCambridgeNumTestNumRoute
  '/ielts-listening/$cambridgeNum/': typeof IeltsListeningCambridgeNumIndexRoute
  '/ielts-reading/$cambridgeNum/': typeof IeltsReadingCambridgeNumIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/speaking-vocab': typeof SpeakingVocabRoute
  '/statistics': typeof StatisticsRoute
  '/test': typeof TestRoute
  '/vocabulary': typeof VocabularyRoute
  '/writing-vocab': typeof WritingVocabRoute
  '/speaking-vocab/test': typeof SpeakingVocabTestRoute
  '/speaking-vocab/view': typeof SpeakingVocabViewRoute
  '/writing-vocab/test': typeof WritingVocabTestRoute
  '/writing-vocab/view': typeof WritingVocabViewRoute
  '/ielts-listening': typeof IeltsListeningIndexRoute
  '/ielts-reading': typeof IeltsReadingIndexRoute
  '/ielts-listening/$cambridgeNum/$testNum': typeof IeltsListeningCambridgeNumTestNumRoute
  '/ielts-reading/$cambridgeNum/$testNum': typeof IeltsReadingCambridgeNumTestNumRoute
  '/ielts-listening/$cambridgeNum': typeof IeltsListeningCambridgeNumIndexRoute
  '/ielts-reading/$cambridgeNum': typeof IeltsReadingCambridgeNumIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ielts-listening': typeof IeltsListeningRouteWithChildren
  '/ielts-reading': typeof IeltsReadingRouteWithChildren
  '/speaking-vocab': typeof SpeakingVocabRoute
  '/statistics': typeof StatisticsRoute
  '/test': typeof TestRoute
  '/vocabulary': typeof VocabularyRoute
  '/writing-vocab': typeof WritingVocabRoute
  '/ielts-listening/$cambridgeNum': typeof IeltsListeningCambridgeNumRouteWithChildren
  '/ielts-reading/$cambridgeNum': typeof IeltsReadingCambridgeNumRouteWithChildren
  '/speaking-vocab_/test': typeof SpeakingVocabTestRoute
  '/speaking-vocab_/view': typeof SpeakingVocabViewRoute
  '/writing-vocab_/test': typeof WritingVocabTestRoute
  '/writing-vocab_/view': typeof WritingVocabViewRoute
  '/ielts-listening/': typeof IeltsListeningIndexRoute
  '/ielts-reading/': typeof IeltsReadingIndexRoute
  '/ielts-listening/$cambridgeNum/$testNum': typeof IeltsListeningCambridgeNumTestNumRoute
  '/ielts-reading/$cambridgeNum/$testNum': typeof IeltsReadingCambridgeNumTestNumRoute
  '/ielts-listening/$cambridgeNum/': typeof IeltsListeningCambridgeNumIndexRoute
  '/ielts-reading/$cambridgeNum/': typeof IeltsReadingCambridgeNumIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ielts-listening'
    | '/ielts-reading'
    | '/speaking-vocab'
    | '/statistics'
    | '/test'
    | '/vocabulary'
    | '/writing-vocab'
    | '/ielts-listening/$cambridgeNum'
    | '/ielts-reading/$cambridgeNum'
    | '/speaking-vocab/test'
    | '/speaking-vocab/view'
    | '/writing-vocab/test'
    | '/writing-vocab/view'
    | '/ielts-listening/'
    | '/ielts-reading/'
    | '/ielts-listening/$cambridgeNum/$testNum'
    | '/ielts-reading/$cambridgeNum/$testNum'
    | '/ielts-listening/$cambridgeNum/'
    | '/ielts-reading/$cambridgeNum/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/speaking-vocab'
    | '/statistics'
    | '/test'
    | '/vocabulary'
    | '/writing-vocab'
    | '/speaking-vocab/test'
    | '/speaking-vocab/view'
    | '/writing-vocab/test'
    | '/writing-vocab/view'
    | '/ielts-listening'
    | '/ielts-reading'
    | '/ielts-listening/$cambridgeNum/$testNum'
    | '/ielts-reading/$cambridgeNum/$testNum'
    | '/ielts-listening/$cambridgeNum'
    | '/ielts-reading/$cambridgeNum'
  id:
    | '__root__'
    | '/'
    | '/ielts-listening'
    | '/ielts-reading'
    | '/speaking-vocab'
    | '/statistics'
    | '/test'
    | '/vocabulary'
    | '/writing-vocab'
    | '/ielts-listening/$cambridgeNum'
    | '/ielts-reading/$cambridgeNum'
    | '/speaking-vocab_/test'
    | '/speaking-vocab_/view'
    | '/writing-vocab_/test'
    | '/writing-vocab_/view'
    | '/ielts-listening/'
    | '/ielts-reading/'
    | '/ielts-listening/$cambridgeNum/$testNum'
    | '/ielts-reading/$cambridgeNum/$testNum'
    | '/ielts-listening/$cambridgeNum/'
    | '/ielts-reading/$cambridgeNum/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IeltsListeningRoute: typeof IeltsListeningRouteWithChildren
  IeltsReadingRoute: typeof IeltsReadingRouteWithChildren
  SpeakingVocabRoute: typeof SpeakingVocabRoute
  StatisticsRoute: typeof StatisticsRoute
  TestRoute: typeof TestRoute
  VocabularyRoute: typeof VocabularyRoute
  WritingVocabRoute: typeof WritingVocabRoute
  SpeakingVocabTestRoute: typeof SpeakingVocabTestRoute
  SpeakingVocabViewRoute: typeof SpeakingVocabViewRoute
  WritingVocabTestRoute: typeof WritingVocabTestRoute
  WritingVocabViewRoute: typeof WritingVocabViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writing-vocab': {
      id: '/writing-vocab'
      path: '/writing-vocab'
      fullPath: '/writing-vocab'
      preLoaderRoute: typeof WritingVocabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speaking-vocab': {
      id: '/speaking-vocab'
      path: '/speaking-vocab'
      fullPath: '/speaking-vocab'
      preLoaderRoute: typeof SpeakingVocabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ielts-reading': {
      id: '/ielts-reading'
      path: '/ielts-reading'
      fullPath: '/ielts-reading'
      preLoaderRoute: typeof IeltsReadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ielts-listening': {
      id: '/ielts-listening'
      path: '/ielts-listening'
      fullPath: '/ielts-listening'
      preLoaderRoute: typeof IeltsListeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ielts-reading/': {
      id: '/ielts-reading/'
      path: '/'
      fullPath: '/ielts-reading/'
      preLoaderRoute: typeof IeltsReadingIndexRouteImport
      parentRoute: typeof IeltsReadingRoute
    }
    '/ielts-listening/': {
      id: '/ielts-listening/'
      path: '/'
      fullPath: '/ielts-listening/'
      preLoaderRoute: typeof IeltsListeningIndexRouteImport
      parentRoute: typeof IeltsListeningRoute
    }
    '/writing-vocab_/view': {
      id: '/writing-vocab_/view'
      path: '/writing-vocab/view'
      fullPath: '/writing-vocab/view'
      preLoaderRoute: typeof WritingVocabViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing-vocab_/test': {
      id: '/writing-vocab_/test'
      path: '/writing-vocab/test'
      fullPath: '/writing-vocab/test'
      preLoaderRoute: typeof WritingVocabTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speaking-vocab_/view': {
      id: '/speaking-vocab_/view'
      path: '/speaking-vocab/view'
      fullPath: '/speaking-vocab/view'
      preLoaderRoute: typeof SpeakingVocabViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speaking-vocab_/test': {
      id: '/speaking-vocab_/test'
      path: '/speaking-vocab/test'
      fullPath: '/speaking-vocab/test'
      preLoaderRoute: typeof SpeakingVocabTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ielts-reading/$cambridgeNum': {
      id: '/ielts-reading/$cambridgeNum'
      path: '/$cambridgeNum'
      fullPath: '/ielts-reading/$cambridgeNum'
      preLoaderRoute: typeof IeltsReadingCambridgeNumRouteImport
      parentRoute: typeof IeltsReadingRoute
    }
    '/ielts-listening/$cambridgeNum': {
      id: '/ielts-listening/$cambridgeNum'
      path: '/$cambridgeNum'
      fullPath: '/ielts-listening/$cambridgeNum'
      preLoaderRoute: typeof IeltsListeningCambridgeNumRouteImport
      parentRoute: typeof IeltsListeningRoute
    }
    '/ielts-reading/$cambridgeNum/': {
      id: '/ielts-reading/$cambridgeNum/'
      path: '/'
      fullPath: '/ielts-reading/$cambridgeNum/'
      preLoaderRoute: typeof IeltsReadingCambridgeNumIndexRouteImport
      parentRoute: typeof IeltsReadingCambridgeNumRoute
    }
    '/ielts-listening/$cambridgeNum/': {
      id: '/ielts-listening/$cambridgeNum/'
      path: '/'
      fullPath: '/ielts-listening/$cambridgeNum/'
      preLoaderRoute: typeof IeltsListeningCambridgeNumIndexRouteImport
      parentRoute: typeof IeltsListeningCambridgeNumRoute
    }
    '/ielts-reading/$cambridgeNum/$testNum': {
      id: '/ielts-reading/$cambridgeNum/$testNum'
      path: '/$testNum'
      fullPath: '/ielts-reading/$cambridgeNum/$testNum'
      preLoaderRoute: typeof IeltsReadingCambridgeNumTestNumRouteImport
      parentRoute: typeof IeltsReadingCambridgeNumRoute
    }
    '/ielts-listening/$cambridgeNum/$testNum': {
      id: '/ielts-listening/$cambridgeNum/$testNum'
      path: '/$testNum'
      fullPath: '/ielts-listening/$cambridgeNum/$testNum'
      preLoaderRoute: typeof IeltsListeningCambridgeNumTestNumRouteImport
      parentRoute: typeof IeltsListeningCambridgeNumRoute
    }
  }
}

interface IeltsListeningCambridgeNumRouteChildren {
  IeltsListeningCambridgeNumTestNumRoute: typeof IeltsListeningCambridgeNumTestNumRoute
  IeltsListeningCambridgeNumIndexRoute: typeof IeltsListeningCambridgeNumIndexRoute
}

const IeltsListeningCambridgeNumRouteChildren: IeltsListeningCambridgeNumRouteChildren =
  {
    IeltsListeningCambridgeNumTestNumRoute:
      IeltsListeningCambridgeNumTestNumRoute,
    IeltsListeningCambridgeNumIndexRoute: IeltsListeningCambridgeNumIndexRoute,
  }

const IeltsListeningCambridgeNumRouteWithChildren =
  IeltsListeningCambridgeNumRoute._addFileChildren(
    IeltsListeningCambridgeNumRouteChildren,
  )

interface IeltsListeningRouteChildren {
  IeltsListeningCambridgeNumRoute: typeof IeltsListeningCambridgeNumRouteWithChildren
  IeltsListeningIndexRoute: typeof IeltsListeningIndexRoute
}

const IeltsListeningRouteChildren: IeltsListeningRouteChildren = {
  IeltsListeningCambridgeNumRoute: IeltsListeningCambridgeNumRouteWithChildren,
  IeltsListeningIndexRoute: IeltsListeningIndexRoute,
}

const IeltsListeningRouteWithChildren = IeltsListeningRoute._addFileChildren(
  IeltsListeningRouteChildren,
)

interface IeltsReadingCambridgeNumRouteChildren {
  IeltsReadingCambridgeNumTestNumRoute: typeof IeltsReadingCambridgeNumTestNumRoute
  IeltsReadingCambridgeNumIndexRoute: typeof IeltsReadingCambridgeNumIndexRoute
}

const IeltsReadingCambridgeNumRouteChildren: IeltsReadingCambridgeNumRouteChildren =
  {
    IeltsReadingCambridgeNumTestNumRoute: IeltsReadingCambridgeNumTestNumRoute,
    IeltsReadingCambridgeNumIndexRoute: IeltsReadingCambridgeNumIndexRoute,
  }

const IeltsReadingCambridgeNumRouteWithChildren =
  IeltsReadingCambridgeNumRoute._addFileChildren(
    IeltsReadingCambridgeNumRouteChildren,
  )

interface IeltsReadingRouteChildren {
  IeltsReadingCambridgeNumRoute: typeof IeltsReadingCambridgeNumRouteWithChildren
  IeltsReadingIndexRoute: typeof IeltsReadingIndexRoute
}

const IeltsReadingRouteChildren: IeltsReadingRouteChildren = {
  IeltsReadingCambridgeNumRoute: IeltsReadingCambridgeNumRouteWithChildren,
  IeltsReadingIndexRoute: IeltsReadingIndexRoute,
}

const IeltsReadingRouteWithChildren = IeltsReadingRoute._addFileChildren(
  IeltsReadingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IeltsListeningRoute: IeltsListeningRouteWithChildren,
  IeltsReadingRoute: IeltsReadingRouteWithChildren,
  SpeakingVocabRoute: SpeakingVocabRoute,
  StatisticsRoute: StatisticsRoute,
  TestRoute: TestRoute,
  VocabularyRoute: VocabularyRoute,
  WritingVocabRoute: WritingVocabRoute,
  SpeakingVocabTestRoute: SpeakingVocabTestRoute,
  SpeakingVocabViewRoute: SpeakingVocabViewRoute,
  WritingVocabTestRoute: WritingVocabTestRoute,
  WritingVocabViewRoute: WritingVocabViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
